### PR TITLE
Add support for backward compatibility

### PR DESCRIPTION
**Pull request by JassJam**
~~Untested, should not leak or throw any error like the pervious version, i'll finish it later on when i'm free~~

### CODE REVIEW

**Comment by JassJam** [comment]
Some subplugins like "dynamic defaults" or "sarysapub3.inc" uses `FindPlugin`, which requires editing ".ff2" to "" and recompiling. Other than that almost all of the subplugins should work fine. (except for KeyValues, use FF2Player.Get*() method)

**Comment by kevyonan** [comment]
how is this coming along? @01Pollux

**Comment by JassJam** [comment]
Almost done I'll notify you once I'm ready, I should also fix the incorrect access of boss index for legacy natives in the include file. 
Btw, do you think that I should implement KeyValues to `freak_fortress_2_old`'s natives? ie loading them to `StringMap` then deleting them once the round end, so far it will just yell at you for not using `Get*()` methods and return 0.

**Comment by JassJam** [comment]
@assyrianic You may merge this if it's all good.

**Pull request merged**
