### PR TITLE
Add OnBossConditionChange forward

### PR DESCRIPTION
**Pull request by Scags**
Was working on a boss and got miffed when I couldn't figure out why disguises were being removed. This was the culprit. 

Proofread me please. I did this in a jiffy.

### CODE REVIEW

**Comment by kevyonan** [comment]
don't forget to update the documentation: `docs/API.md`

**Comment by Scags** [comment]
Added.

**Comment by Scags** [comment]
Had a stroke on that last commit. Fixed.

**Comment by kevyonan** [comment]
I wanna say, can you make a general forward called `OnBossConditionChange` or `OnVSH2ConditionChange` with a `bool` that represents whether the condition was removed?

Something like:
```c
function Action (const VSH2Player player, const TFCond cond, const bool removing);
```

**Pull request merged**
